### ISSUE TITLE
PEP8 and Pylint

### ISSUE THREAD

**Issue by fourstix** [sparkfun/Qwiic_Keypad_Py#1]
I noticed the code isn't following the Python code conventions documented in PEP8.  https://www.python.org/dev/peps/pep-0008/

Was it intentional for the Qwiic_Keypad_Py code to follow C/Java conventions rather Python conventions?  For example Python method and function names in PEP8 should be all lower case words separated by underscores, 'is_connected()' rather than 'isConnected()'.  Even better would be to define a property named 'connected' instead of a method.

One can run pylint to find style issues with PEP8. (PEP8 and pylint are extremely picky but they do result in maintainable and readable code.)

I thought I'd mention this, since many python programmers consider it best practice to follow PEP8.  CircuitPython requires the code to pass pylint as part of their community build process.

**Comment by fourstix** [comment]
Of course, if you want to keep some method names in camel case form for compatibility with the Arduino version of the libraries, you can just use the comment #pylint: disable=invalid-name to override the check.

That might make sense for isConnect().  After all, real programmers can program FORTRAN in any language.

**Comment by ghost** [comment]
This is completely a spot on comment and something we missed, since we were focused on porting the existing libs. 

We're going to refactor everything over the next week to use a more conventional naming structure.

**Comment by ghost** [comment]
And we've updated this repo to this just now.
